//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolingRoomManagement.Areas.PurchaseOrderManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseOrderRequestImage
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> IdRequestItem { get; set; }
        public string ImageName { get; set; }
        public string Directory { get; set; }
    }
}
