//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolingRoomManagement.Areas.PurchaseOrderManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseOrderRequest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PurchaseOrderRequest()
        {
            this.PurchaseOrderRequestItems = new HashSet<PurchaseOrderRequestItem>();
        }
    
        public System.Guid Id { get; set; }
        public string RequestDepartment { get; set; }
        public string UseDepartment { get; set; }
        public string CostCode { get; set; }
        public string LegalEntity { get; set; }
        public string DeliveryLocation { get; set; }
        public string PlanDeliveryDate { get; set; }
        public string Requester { get; set; }
        public string RequesterPhoneNumber { get; set; }
        public string RequesterEmail { get; set; }
        public string Approver { get; set; }
        public string Reviewer { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseOrderRequestItem> PurchaseOrderRequestItems { get; set; }
    }
}
