//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolingRoomManagement.Areas.PurchaseOrderManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseOrderRequestItem
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> IdPORequest { get; set; }
        public string ProductName { get; set; }
        public string Brand { get; set; }
        public string Information { get; set; }
        public string Unit { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string Type { get; set; }
        public string MaterialCode { get; set; }
        public string ReferencePriceLink { get; set; }
        public string Notes { get; set; }
        public string Feedback { get; set; }
    
        public virtual PurchaseOrderRequest PurchaseOrderRequest { get; set; }
    }
}
