//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolingRoomManagement.Areas.PurchaseOrderManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int id { get; set; }
        public string username { get; set; }
        public string fullname { get; set; }
        public Nullable<int> part_id { get; set; }
        public string phone { get; set; }
        public string mail { get; set; }
        public Nullable<int> role_id { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
        public string password { get; set; }
        public string chinese_name { get; set; }
    }
}
