//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolingRoomManagement.Areas.NVIDIA.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DevicePR
    {
        public int Id { get; set; }
        public Nullable<int> IdPurchaseRequest { get; set; }
        public Nullable<int> IdDevice { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string PR_No { get; set; }
        public string PO_No { get; set; }
        public Nullable<int> PR_Quantity { get; set; }
        public Nullable<System.DateTime> PR_CreatedDate { get; set; }
        public Nullable<System.DateTime> PO_CreatedDate { get; set; }
        public Nullable<int> IdUserCreated { get; set; }
        public Nullable<System.DateTime> ETD_Date { get; set; }
        public Nullable<System.DateTime> ETA_Date { get; set; }
        public Nullable<System.DateTime> ATA_Date { get; set; }
        public string Status { get; set; }
    
        public virtual Device Device { get; set; }
        public virtual User UserCreated { get; set; }
    }
}
