//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolingRoomManagement.Areas.NVIDIA.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Warehouse
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Warehouse()
        {
            this.Devices = new HashSet<Device>();
            this.WarehouseLayouts = new HashSet<WarehouseLayout>();
        }
    
        public int Id { get; set; }
        public string WarehouseName { get; set; }
        public string Description { get; set; }
        public Nullable<int> IdUserManager { get; set; }
        public string Factory { get; set; }
        public Nullable<int> Floors { get; set; }
        public Nullable<int> IdUserDeputy1 { get; set; }
        public Nullable<int> IdUserDeputy2 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Device> Devices { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WarehouseLayout> WarehouseLayouts { get; set; }
        public virtual User UserDeputy1 { get; set; }
        public virtual User UserDeputy2 { get; set; }
    }
}
