//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolingRoomManagement.Areas.NVIDIA.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class WarehouseLayout
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WarehouseLayout()
        {
            this.DeviceWarehouseLayouts = new HashSet<DeviceWarehouseLayout>();
        }
    
        public int Id { get; set; }
        public Nullable<int> IdWareHouse { get; set; }
        public string Line { get; set; }
        public string Floor { get; set; }
        public string Cell { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeviceWarehouseLayout> DeviceWarehouseLayouts { get; set; }
    }
}
