//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolingRoomManagement.Areas.NVDIA.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Device
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Device()
        {
            this.HistoryUpdateDevices = new HashSet<HistoryUpdateDevice>();
        }
    
        public int Id { get; set; }
        public string DeviceCode { get; set; }
        public string DeviceName { get; set; }
        public Nullable<System.DateTime> DeviceDate { get; set; }
        public Nullable<double> Buffer { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string Type { get; set; }
        public string Status { get; set; }
        public Nullable<int> IdWareHouse { get; set; }
        public Nullable<int> IdGroup { get; set; }
        public Nullable<int> IdVendor { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        public virtual Group Group { get; set; }
        public virtual Vendor Vendor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HistoryUpdateDevice> HistoryUpdateDevices { get; set; }
    }
}
